### ISSUE TITLE
Quickstart broken - references non-existent crate

### ISSUE THREAD

**Issue by bacoboy** [seed-rs/seed-quickstart#14]
[this commit](https://github.com/seed-rs/seed-quickstart/commit/a00625a7333928fd55e8916e9b928d327b64c3ef) updates the seed crate to 0.6.0 or later.  There is no 0.6.0 crate released as of time of writing.  This commit should be reverted or moved to a working branch until 0.6.0 is out.

**Comment by MartinKavik** [comment]
@David-OConnor Please release Seed before updating other projects and docs + use PRs, it's confusing for users and even for me a little bit, thank you!

**Comment by David-OConnor** [comment]
0.6.0 released
