### ISSUE TITLE
cargo make build does not work

### ISSUE THREAD

**Issue by stevejb71** [seed-rs/seed-quickstart#16]
```[cargo-make] INFO - Execute Command: "wasm-pack" "build" "--target" "web" "--out-name" "package" "--dev"
error: Found argument '--out-name' which wasn't expected, or isn't valid in this context
	Did you mean --out-dir?```

**Comment by David-OConnor** [comment]
Try updating cargo make: `cargo install --force cargo-make`

**Comment by stevejb71** [comment]
Looks like I had an outdated version of wasm-pack. After downloading the latest it worked fine.
Thanks for your quick response - I'll close the issue.

**Comment by MartinKavik** [comment]
@stevejb71 Thanks for the issue!
I've added it into https://github.com/seed-rs/seed-quickstart/issues/11#issuecomment-592926600.
And I'll prevent it in https://github.com/MartinKavik/seeder.
