### ISSUE TITLE
How does one package a release from seed-quickstart?

### ISSUE THREAD

**Issue by itsgreggreg** [seed-rs/seed-quickstart#17]
What command do I run to generate a folder I can plop on a webserver and show others what I've built?

**Comment by MartinKavik** [comment]
See https://github.com/seed-rs/seed-quickstart/pull/18/files.
Thanks for the issue!

**Comment by itsgreggreg** [comment]
Sweet, thank you very much!

Here's a little mortgage monthly payment calculator I wrote to explore seed:
http://stuff.greg.lol/monthly-payment-calculator/

And here's the source:
https://gitlab.com/greggreg/monthly-payment-calculator

**Comment by MartinKavik** [comment]
@itsgreggreg Nice code and architecture, feel free to create a PR to https://github.com/seed-rs/awesome-seed-rs.
