### ISSUE TITLE
Every file marked executable

### ISSUE THREAD

**Issue by Xandaros** [seed-rs/seed-quickstart#35]
Every single file is marked as executable, when none of them should be.

**Comment by MartinKavik** [comment]
Why is it important?
Do you know how we can mark them automatically (including Windows)?

**Comment by Xandaros** [comment]
Well, in a console it is confusing when every file is green instead of the usual white.
People using a GUI would try to execute them with a double-click instead of opening them in an editor, so that is also not ideal.

And I don't know Windows, sorry.

**Comment by MartinKavik** [comment]
Should be resolved by https://github.com/seed-rs/seed-quickstart/pull/36. Closing.
